Tosca parser integration
xlab-si/xopera-tosca-parser pull request #5
Opened 2022-05-04 11:49 UTC by alexmaslenn

2022-05-16 12:31 UTC, anzoman requested changes
Looks okay, @alexmaslenn - just add the docs + typing and we're done here.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/template/node.py
> +    def is_a(self, typ):
Currently all the xOpera TOSCA parser's code is documented and typed I'd like to keep it that way.

Please insert documentation string stub with the similar style as other functions + also add typing everywhere.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/template/node.py
> +    def instance(self):
Please insert documentation string stub with the similar style as other functions.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/template/node.py
> +    def instance(self, value):
Please insert documentation string stub with the similar style as other functions.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/template/relationship.py
> +    def is_a(self, typ):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/template/relationship.py
> +    def instance(self):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/template/relationship.py
> +    def instance(self, value):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def dump(self):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def load(self, data):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def data(self):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def copy(self):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def unset(self):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def eval(self, instance, key):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def is_function(self):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def check_function(data):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def eval_function(data, instance):
Docs missing.

2022-05-16 12:31 UTC, anzoman commented on src/opera_tosca_parser/value.py
> +    def check_eval_function(data, instance):
Docs missing.

2022-05-18 15:33 UTC, alexmaslenn commented
Thanks @anzoman for your review. Docs and typing added.

2022-05-19 07:46 UTC, anzoman approved these changes
Thanks @alexmaslenn, let's merge this!

2022-05-19 07:46 UTC, merged